#+TITLE: Ejercicios 02
#+AUTHOR: DiegoAGtz
#+DATE: <2022-02-08 mar.>

* Ejercicio 01
Solicitar por la terminal 10 calificaciones para un alumno y calcular su promedio

#+begin_src js :tangle exercises_02.js
const prompt = require('prompt-sync')();
console.log('Ejercicio 01');

let promedio = 0;
for (let i = 0; i < 10; i++) {
  let cal = prompt(`Ingresa la calificación ${i+1}: `);
  promedio += Number(cal);
}
promedio /= 10;
console.log(`El promedio es ${promedio}`);
#+end_src

* Ejercicio 02
Escribir un programa que imprima los numéros pares entre 1 y un número entero dado por el usuario

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 02');

let limite = prompt('Ingresa un número entero: ');
for (let i = 1; i < Number(limite); i++) {
  console.log(`${i}`);
}
#+end_src

* Ejercicio 03
Solicitar 10 edades y decir cuántos menores y mayores de edad hay

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 03');

let menores = 0;
let mayores = 0;
for (let i = 0; i < 10; i++) {
  let edad = prompt(`Ingresa la edad ${i+1}: `);
  (Number(edad) < 18) ? menores++ : mayores++;
}
console.log(`Hay ${menores} menores de edad y ${mayores} mayores de edad.`);
#+end_src

* Ejercicio 04
Solicitar n números enteros y decir cuántos son pares, cuántos impares, cuántos negativos, cuantos positivos y cuántos ceros

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 04');

let n = prompt('Cantidad de números a ingresar: ');

let pares = 0;
let impares = 0;
let positivos = 0;
let negativos = 0;
let ceros = 0;

for (let i = 0; i < n; i++) {
  let numero = prompt(`Ingresa el número ${i+1}: `);

  (Number(numero)%2 == 0) ? pares++ : impares++;

  if (Number(numero) > 0) positivos++;
  else if (Number(numero) < 0) negativos++;
  else ceros++;
}

console.log('')
console.log(`Ingresaste ${pares} números pares`);
console.log(`Ingresaste ${impares} números impares`);
console.log(`Ingresaste ${positivos} números positivos`);
console.log(`Ingresaste ${negativos} números negativos`);
console.log(`Ingresaste ${ceros} ceros`);
#+end_src

* Ejercicio 05
Solicitar 2 números y calcular su producto por sumas sucesivas

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 05');

let n1 = prompt('Ingresa el número 1: ');
let n2 = prompt('Ingresa el número 2: ');
let producto = 0;

for (let i = 0; i < n2; i++) {
  producto += Number(n1);
}

console.log(`${n1} x ${n2} = ${producto}`);
#+end_src

* Ejercicio 06
Solicitar n calificaciones, encontrar las calificaciones menor y mayor

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 06');

let n = prompt('Cantidad de calificaciones a ingresar: ');
let min;
let max;

for (let i = 0; i < Number(n); i++) {
  let cal = prompt(`Ingresa la calificacion ${i+1}: `);
  if (i==0) {
    min = Number(cal);
    max = Number(cal);
    continue;
  }
  if (Number(cal) < min) {
    min = Number(cal);
  } else if (Number(cal) > max) {
    max = Number(cal);
  }
}

console.log('');
if (min != undefined) {
  console.log(`La calificación más alta es: ${max}`);
  console.log(`La calificación más baja es: ${min}`);
} else console.log('No ingresó calificaciones.')
#+end_src

* Ejercicio 07
Una persona deposita una cantidad n en un banco a m meses, el banco le paga un porcentaje p de interés mensual. Calcular cuanto tendrá en su cuenta al finalizar el periodo.

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 07');

let deposito = prompt('Cantidad a depositar: ');
let meses = prompt('Meses que durará el deposito: ');
let porcentaje = prompt('Interés mensual: ');

let total = Number(deposito);
for (let i = 0; i < Number(meses); i++) {
  total += total * Number(porcentaje)/100;
}

console.log(`El total en tu cuenta al finalizar el periodo es ${total}`);
#+end_src

* Ejercicio 08
Una persona adquirió un producto para pagar en 20 meses. El primer mes pagó $10, el segundo $20, el tercero $40 y así sucesivamente (múltiplos de 2). Calcular cada pago mensual y el total de lo que pagó después de los 20 meses.

#+begin_src js
console.log('Ejercicio 08');
let total = 0;

for (let i = 0; i < 20; i++) {
  let mensual = 2**i * 10;
  total += mensual;
  console.log(`El mes ${i+1} pagó ${mensual}`);
}

console.log(`El total que pagó fue de ${total}`);
#+end_src

* Ejercicio 09
A partir de una población n (enteros) de individuos, se tiene una epidemia en donde el día 1 muere 1 persona, el día 2 mueren 2 personas, el día 3 mueren 4 personas, etc. Usando un ciclo while, calcular en cuántos días se moriría toda la población.

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 09');

let n = prompt(`Número de individuos: `);
n = Number(n);
let i = 0;

while (n > 0) {
  n -= 2**(++i - 1);
}

console.log(`Población muerta en ${i} días.`);
#+end_src

* Ejercicio 10
Pedir una cantidad entera que equivale a un número de días e indicar a cuantos años, meses y dís corresponde. Considerar que un mes tiene 30 días.

#+begin_src js
const prompt = require('prompt-sync')();
console.log('Ejercicio 10');
let ndias = prompt('Ingrese una cantidad de días: ');

let anios = (ndias - ndias%365) / 365;
let meses = ((ndias - anios*365) - (ndias - anios*365) % 30) / 30;
let dias =  ndias - anios*365 - meses*30;
console.log(`${ndias} días corresponde a ${anios} año(s), ${meses} mes(es) y ${dias} día(s).`)

anios = Math.floor(ndias / 365);
meses = Math.floor((ndias - anios*365) / 30);
dias = ndias - anios*365 - meses*30;
console.log(`${ndias} días corresponde a ${anios} año(s), ${meses} mes(es) y ${dias} día(s).`)
#+end_src

* Ejercicio 11
Dado un array con número flotantes (crea un array por tu cuenta), escribe un programa que devuelve todos los valores que sean mayores que un número dado (defínelo tú).

#+begin_src js
console.log('Ejercicio 11');
let arr = [10.4, 1.4, 12.6, 17.3, 0.35, 64.1, 75.3, 11.5, 1.4, 75.1, 2.4, 53.1, 31.7];
let n = 9.6;
let mayores = new Array();

arr.forEach(item => {
  if (item > n) mayores.push(item)
});

mayores.forEach(item => console.log(item))
#+end_src

* Ejercicio 12
Dado un array lleno con números flotantes (crea un array por tu cuenta), escribe un programa que calcule la suma y el promedio de todos los elementos.

#+begin_src js
console.log('Ejercicio 12');
let arr = [10.4, 1.4, 12.6, 17.3, 0.35, 64.1, 75.3, 11.5, 1.4, 75.1, 2.4, 53.1, 31.7];
let sum = 0;

arr.forEach(item => sum += item);

console.log(`La suma es: ${sum}`);
console.log(`El promedio es: ${sum/arr.length}`);
#+end_src

* Ejercicio 13
Dado un array lleno con números enteros (crea un array por tu cuenta), escribe un programa que encuentre cuáles son los valores mayor y menor.

#+begin_src js
console.log('Ejercicio 13');
let arr = [10, 1, 12, 17, 35, 64, 75, 11, 4, 501, 24, 0, 31, 97];
let max = arr[0];
let min = arr[0];

arr.forEach(item => {
  if (item < min) min = item;
  else if (item > max) max = item;
});

console.log(`El elemento más pequeño es ${min}`)
console.log(`El elemento más grande es ${max}`)
#+end_src

* Ejercicio 14
Dado un array de tres números enteros (crea un array por tu cuenta), escribe un programa que determine si el array está ordenado en orden ascendente o descendente, o si no está ordenado.

#+begin_src js
console.log('Ejercicio 14');
let arr = [5, 1, 0];
let asc = true;
let desc = true;

for (let i = 1; i < arr.length; i++) {
  if (asc || desc) {
    if (!(asc && arr[i] >= arr[i-1])) asc = false;
    if (!(desc && arr[i] <= arr[i-1])) desc = false;
  } else break;
}

if (!(asc || desc)) console.log('El array esta desordenado');
else console.log(`El array esta ordenado de forma ${asc ? 'ascendente' : 'descendente'}`);
#+end_src
